databases:
  - name: hrms-db
    plan: basic_256mb
    region: frankfurt

services:
  - type: web
    name: hrms-api
    runtime: docker
    plan: starter
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://hrms.mulkinternational.co,https://hrms-mulk.vercel.app
      - key: APP_PUBLIC_URL
        value: https://hrms.mulkinternational.co
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: BLOB_ACCESS
        value: public
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
